name: Publish Canary Packages

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: 'Publish Canary Packages'
    environment: npm deploy
    timeout-minutes: 15
    runs-on: ubuntu-latest-16-cores-open

    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Run our setup
        uses: ./.github/actions/setup

      - name: Publish Canary Packages
        run: yarn tsx ./scripts/publish-canary.ts
        env:
          GH_TOKEN: ${{ github.token }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
