name: (Re)Publish public packages manually
# This only attempts to publish the public packages to npm.
# It does not bump the version, it does not update the changelogs, it does not create a github release.

# Package publishing is manually triggered on github actions dashboard
on: workflow_dispatch

jobs:
  deploy:
    name: '(Re)Publish public packages manually'
    environment: npm deploy
    timeout-minutes: 15
    runs-on: ubuntu-latest-16-cores-open

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Run our setup
        uses: ./.github/actions/setup

      - name: Publish
        run: yarn tsx ./scripts/publish-manual.ts
        env:
          GH_TOKEN: ${{ github.token }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
