import BarsFade from '@/assets/icons/Spinner/BarsFade.svg';
import BarsRotateFade from '@/assets/icons/Spinner/BarsRotateFade.svg';
import BarsScale from '@/assets/icons/Spinner/BarsScale.svg';
import BarsScaleFade from '@/assets/icons/Spinner/BarsScaleFade.svg';
import BarsScaleMiddle from '@/assets/icons/Spinner/BarsScaleMiddle.svg';
import BlocksScale from '@/assets/icons/Spinner/BlocksScale.svg';
import BlocksShuffle2 from '@/assets/icons/Spinner/BlocksShuffle2.svg';
import BlocksShuffle3 from '@/assets/icons/Spinner/BlocksShuffle3.svg';
import BlocksWave from '@/assets/icons/Spinner/BlocksWave.svg';
import BouncingBall from '@/assets/icons/Spinner/BouncingBall.svg';
import Clock from '@/assets/icons/Spinner/Clock.svg';
import DotRevolve from '@/assets/icons/Spinner/DotRevolve.svg';
import Eclipse from '@/assets/icons/Spinner/Eclipse.svg';
import EclipseHalf from '@/assets/icons/Spinner/EclipseHalf.svg';
import GooeyBalls1 from '@/assets/icons/Spinner/GooeyBalls1.svg';
import GooeyBalls2 from '@/assets/icons/Spinner/GooeyBalls2.svg';
import Pulse from '@/assets/icons/Spinner/Pulse.svg';
import Pulse2 from '@/assets/icons/Spinner/Pulse2.svg';
import Pulse3 from '@/assets/icons/Spinner/Pulse3.svg';
import PulseMultiple from '@/assets/icons/Spinner/PulseMultiple.svg';
import PulseRing from '@/assets/icons/Spinner/PulseRing.svg';
import PulseRings2 from '@/assets/icons/Spinner/PulseRings2.svg';
import PulseRings3 from '@/assets/icons/Spinner/PulseRings3.svg';
import PulseRingsMultiple from '@/assets/icons/Spinner/PulseRingsMultiple.svg';
import RingResize from '@/assets/icons/Spinner/RingResize.svg';
import Tadpole from '@/assets/icons/Spinner/Tadpole.svg';
import Wifi from '@/assets/icons/Spinner/Wifi.svg';
import WifiFade from '@/assets/icons/Spinner/WifiFade.svg';
import WindToy from '@/assets/icons/Spinner/WindToy.svg';
import _12DotsScaleRotate from '@/assets/icons/Spinner/_12DotsScaleRotate.svg';
import _180Ring from '@/assets/icons/Spinner/_180Ring.svg';
import _180RingWithBg from '@/assets/icons/Spinner/_180RingWithBg.svg';
import _270Ring from '@/assets/icons/Spinner/_270Ring.svg';
import _270RingWithBg from '@/assets/icons/Spinner/_270RingWithBg.svg';
import _3DotsBounce from '@/assets/icons/Spinner/_3DotsBounce.svg';
import _3DotsFade from '@/assets/icons/Spinner/_3DotsFade.svg';
import _3DotsMove from '@/assets/icons/Spinner/_3DotsMove.svg';
import _3DotsRotate from '@/assets/icons/Spinner/_3DotsRotate.svg';
import _3DotsScale from '@/assets/icons/Spinner/_3DotsScale.svg';
import _3DotsScaleMiddle from '@/assets/icons/Spinner/_3DotsScaleMiddle.svg';
import _6DotsRotate from '@/assets/icons/Spinner/_6DotsRotate.svg';
import _6DotsScale from '@/assets/icons/Spinner/_6DotsScale.svg';
import _6DotsScaleMiddle from '@/assets/icons/Spinner/_6DotsScaleMiddle.svg';
import _8DotsRotate from '@/assets/icons/Spinner/_8DotsRotate.svg';
import _90Ring from '@/assets/icons/Spinner/_90Ring.svg';
import _90RingWithBg from '@/assets/icons/Spinner/_90RingWithBg.svg';
import { IconSet } from '@/components';
export const SpinnerIconSet: IconSet = {
  BarsFade, BarsRotateFade, BarsScale, BarsScaleFade, BarsScaleMiddle, BlocksScale, BlocksShuffle2, BlocksShuffle3, BlocksWave, BouncingBall, Clock, DotRevolve, Eclipse, EclipseHalf, GooeyBalls1, GooeyBalls2, Pulse, Pulse2, Pulse3, PulseMultiple, PulseRing, PulseRings2, PulseRings3, PulseRingsMultiple, RingResize, Tadpole, Wifi, WifiFade, WindToy, _12DotsScaleRotate, _180Ring, _180RingWithBg, _270Ring, _270RingWithBg, _3DotsBounce, _3DotsFade, _3DotsMove, _3DotsRotate, _3DotsScale, _3DotsScaleMiddle, _6DotsRotate, _6DotsScale, _6DotsScaleMiddle, _8DotsRotate, _90Ring, _90RingWithBg
};
// Spinner - https://github.com/n3r4zzurr0/svg-spinners - 46 Icons
